### ISSUE TITLE
The content is displayed in the wrong place

### ISSUE THREAD

**Issue by patou** [Muffo/fullyfeedly#21] opened 2016-09-01 09:27 UTC
When I click on the 
![fullyfeedly](https://cloud.githubusercontent.com/assets/841858/18162467/dfb63712-7036-11e6-9167-f80885a87b21.png)

The content is displayed on the top of the list of article behind of the tab :

![fullyfeedly loaded](https://cloud.githubusercontent.com/assets/841858/18162466/dfb11c0a-7036-11e6-9ec2-2923627d3b93.png)

**Comment by Muffo** [comment] 2016-09-01 09:52
Hi @patou 

Thanks a lot for reporting the issue!
The images are very useful to understand what's going on.

Is this happening with all the websites or only a few particular ones?

Unfortunately I'll be travelling for the next 2 weeks and I don't have access to the laptop with all the tools required to build the extension.

**Comment by patou** [comment] 2016-09-01 12:47
@Muffo I created a pull request with a correct that work for me.
Maybe it's not work on your feedly, because I think I use a beta channel feedly.

**Comment by Muffo** [comment] 2016-09-02 12:56
Thanks a lot for proposing a fix!

I agree that the issue is probably visible only in the beta channel.
My suggestion would be to keep the pull request open until they roll the changes to the public version.


What do you think?

**Comment by patou** [comment] 2016-09-19 15:35
Can you look at your feedly if you have the class "u100Entry" ?
If not, we can change the code tu check if the class u100Entry exist, otherwise look at the old .content class.

**Comment by Muffo** [comment] 2016-09-19 19:38
I have just searched the class ".u100Entry" and in my version of feedly the div contains not only the text but also the title and the header.

For example:

<img width="682" alt="schermata 2016-09-19 alle 20 34 29" src="https://cloud.githubusercontent.com/assets/538925/18646282/c1572710-7ea8-11e6-9f59-b1bb9571c3d6.png">

**Comment by patou** [comment] 2016-09-19 19:49
Yes, I my version also.
I search after the class ".entryBody".
Do you have the ".entryBody" in the ".u100Entry" ?
If not, we can check with this class.

**Comment by Muffo** [comment] 2016-09-19 20:12
Yes, `.entryBody` is inside the `.u100Entry`

<img width="773" alt="schermata 2016-09-19 alle 21 11 46" src="https://cloud.githubusercontent.com/assets/538925/18647406/bc455da0-7ead-11e6-9023-56830dea1376.png">

**Comment by sk123** [comment] 2016-11-14 17:37
I am having this exact issue.  It worked perfectly just a couple days ago.  I just posted a note about the issue in the chrome web store, but the description here is much more accurate than mine.  Thanks for all your work.

**Comment by Muffo** [comment] 2016-11-14 20:54
Working on this now :)

**Comment by Muffo** [comment] 2016-11-14 21:05
This has been fixed in release `0.9.1`

**Closed** 2016-11-14 21:08 UTC
Labels: bug

**Comment by sk123** [comment] 2016-11-14 21:24
Thank you so much!

**Comment by sk123** [comment] 2016-11-14 21:31
New issue - there's no spacing between paragraphs anymore.  You rock.

**Comment by sk123** [comment] 2016-11-14 21:39
That's boilerplate only - perfectly happy using Mercury.  Thanks again.
